services:
  adstart-server:
    build:
      context: ./Adstart-Media-Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./Adstart-Media-Backend/.env
  adstart-frontend:
    build:
      context: ./Adstart-Media-Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./Adstart-Media-Frontend/.env
    volumes:
      - ./Adstart-Media-Frontend:/app
      - /app/node_modules
  adstart-admin:
    build:
      context: ./Adstart-Media-Admin
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    env_file:
      - ./Adstart-Media-Admin/.env
    volumes:
      - ./Adstart-Media-Admin:/app
      - /app/node_modules